name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    env:
      NOME_IMAGEM: apicontagem-preview8
      IMAGEM_AZURE: ${{ secrets.AZURE_CONTAINER_REGISTRY_SERVER }}/$NOME_IMAGEM

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login no Azure Container Registry
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
        login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_SERVER }}

    - name: Build e Push no Docker Hub + Azure Container Registry
      run: |
        cd ./APIContagem
        docker build . --file Dockerfile --tag ${{ env.IMAGEM_AZURE }}:latest
        docker tag ${{ env.IMAGEM_AZURE }}:latest ${{ env.IMAGEM_AZURE }}:$GITHUB_RUN_NUMBER
        docker push ${{ env.IMAGEM_AZURE }}
        docker images
        
    - name: Login no Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure WebApp - Deployment da Aplicacao
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.NOME_WEBAPP }}
        images: 'groffegithubactions.azurecr.io/apicontagem-preview8:latest'
